const fs = require('fs-extra');
const path = require('path');

// This is a simple demo script to test the project generation
// In a real scenario, this would be called from the VS Code extension

console.log('🎉 Edino Project Generator Extension Demo');
console.log('==========================================');

// Simulate the extension functionality
async function demoProjectGeneration() {
  try {
    const projectName = 'demo-project';
    const projectType = 'frontend'; // or 'backend', 'fullstack'
    const targetPath = path.join(__dirname, 'demo-output', projectName);

    console.log(`\n📁 Creating ${projectType} project: ${projectName}`);
    console.log(`📍 Target path: ${targetPath}`);

    // Create demo output directory
    await fs.ensureDir(path.dirname(targetPath));

    // Simulate project structure creation
    const folders = [
      'src',
      'src/components',
      'src/pages',
      'src/assets',
      'public',
      'docs'
    ];

    console.log('\n📂 Creating folder structure...');
    for (const folder of folders) {
      const folderPath = path.join(targetPath, folder);
      await fs.ensureDir(folderPath);
      console.log(`  ✅ Created: ${folder}`);
    }

    // Create sample files
    const files = [
      {
        path: 'README.md',
        content: `# ${projectName}\n\nThis is a demo project generated by Edino Extension.\n\n## Getting Started\n\n1. Install dependencies\n2. Start development server\n3. Build for production\n`
      },
      {
        path: 'package.json',
        content: JSON.stringify({
          name: projectName,
          version: '1.0.0',
          description: 'Demo project',
          scripts: {
            start: 'echo "Project started!"',
            build: 'echo "Project built!"'
          }
        }, null, 2)
      },
      {
        path: '.gitignore',
        content: 'node_modules/\n.env\n.DS_Store\n'
      }
    ];

    console.log('\n📄 Creating sample files...');
    for (const file of files) {
      const filePath = path.join(targetPath, file.path);
      await fs.ensureDir(path.dirname(filePath));
      await fs.writeFile(filePath, file.content, 'utf8');
      console.log(`  ✅ Created: ${file.path}`);
    }

    console.log('\n🎉 Project generation completed successfully!');
    console.log(`\n📂 Project location: ${targetPath}`);
    console.log('\n🚀 Next steps:');
    console.log('  1. Open the project in VS Code');
    console.log('  2. Install dependencies: npm install');
    console.log('  3. Start development: npm start');

  } catch (error) {
    console.error('❌ Error generating project:', error);
  }
}

// Run the demo
demoProjectGeneration();
